name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 4.0.0-nullsafety
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http_parser: ^4.0.0-nullsafety
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  # test: ^1.5.1
  pedantic: ^1.10.0-nullsafety.3
  # test_coverage: ^0.4.1
#  flutter_test:
#    sdk: flutter

